Repository IGNF/route-graph-generator, pull requests merged in 2023-04, with the labels that each got.

#51 fix(road2config): default value for pop to avoid exception
  r2gg/_main.py
Labels: bug

#50 fix(ci): update supported tag version to x.y.z
  .github/workflows/docker_publish.yml
Labels: bug, CI

#56 [ci] delete doc deployment on tags
  .github/workflows/docker_publish.yml
  .github/workflows/documentation.yml
  changelog.md
Labels: CI
