Repository IGNF/route-graph-generator, pull requests merged in 2023-01, with the labels that each got.

#19 feat(doc) Add doc generation with sphinx
  changelog.md
  docker/readme.md
  docs/.gitignore
  docs/conf.py
  docs/development/documentation.md
  docs/development/history.md
  docs/docker/debian/readme.md
  docs/docker/readme.md
  docs/index.md
  docs/sql/readme.md
  docs/usage/configuration.md
  docs/usage/r2gg.md
  requirements.txt
  requirements/documentation.txt
Labels: documentation, sprint1

#25 feat(ci): add docker image publish in github container registry
  .github/workflows/docker_publish.yml
Labels: sprint1, CI

#28 feat(docker): update python version to 3.10.9
  docker/debian/Dockerfile
Labels: enhancement, sprint1
