Repository IGNF/route-graph-generator, pull requests merged in 2023-03, with the labels that each got.

#30 feat(ci): add publish of package in test pypi and pypi for tags
  .github/workflows/pypi_publish.yml
  README.md
  setup.py
Labels: CI

#38 Feature/add cli test
  .github/workflows/unit-test.yml
  docs/development/testing.md
  r2gg/_configure.py
  requirements/testing.txt
  setup.cfg
  tests/config/bdtopo_base.json
  tests/config/pivot_base.json
  tests/config/sql2pivot.json
  tests/dev/docker-compose.dev.yml
  tests/test_cli.py
Labels: CI, test

#43 [fix] ignore files created by tests
  .gitignore
  tests/.gitignore
  tests/config/.gitignore
Labels: bug

#48 feat(json-schema):add cost_calculations file json-schema
  r2gg/json-schema/cost_calculations.schema.json
Labels: documentation
